name: Push Workflow

on:
 push:
  branches:
   - main

jobs:
 hello:
  runs_on: ubuntu-latest
  steps:
      - name: Say Hello
        run: echo "Hello! This workflow runs on every push to main."
   
  


   
